function createMenu()
    % Vytvoření hlavního okna (GUI)
    fig = uifigure('Name', 'Heuristická optimalizace', 'Position', [400 200 400 620]);

    % Popisek
    lbl = uilabel(fig, ...
        'Text', 'Vítejte v programu pro optimalizaci', ...
        'Position', [50 590 300 30], ...
        'HorizontalAlignment', 'center', ...
        'FontSize', 14);

    % Dropdown menu: Výběr funkce
    uilabel(fig, ...
        'Text', 'Vyberte optimalizační funkci:', ...
        'Position', [100 550 200 30], ...
        'HorizontalAlignment', 'center', ...
        'FontSize', 12);
    
    dropdownFun = uidropdown(fig, ...
        'Items', {'f1', 'f2', 'f3', 'f4'}, ...
        'Position', [100 510 200 30]);

    % Dropdown menu: Výběr tvaru okolí
    uilabel(fig, ...
        'Text', 'Vyberte tvar okolí:', ...
        'Position', [100 480 200 30], ...
        'HorizontalAlignment', 'center', ...
        'FontSize', 12);
    
    dropdownShape = uidropdown(fig, ...
        'Items', {'Kruh', 'Čtverec'}, ...
        'Position', [100 450 200 30]);

    % Textové pole pro zadání velikosti okolí
    uilabel(fig, ...
        'Text', 'Zadejte velikost okolí (poloměr/strana):', ...
        'Position', [100 420 200 30], ...
        'HorizontalAlignment', 'center', ...
        'FontSize', 12);

    sizeField = uieditfield(fig, 'numeric', ...
        'Position', [100 390 200 30]);

    % Pole pro zadání omezení x1
    uilabel(fig, ...
        'Text', 'Omezení x1 (min a max):', ...
        'Position', [100 360 200 30], ...
        'HorizontalAlignment', 'center', ...
        'FontSize', 12);

    x1MinField = uieditfield(fig, 'numeric', ...
        'Placeholder', 'Min x1', ...
        'Position', [100 330 90 30]);

    x1MaxField = uieditfield(fig, 'numeric', ...
        'Placeholder', 'Max x1', ...
        'Position', [210 330 90 30]);

    % Pole pro zadání omezení x2
    uilabel(fig, ...
        'Text', 'Omezení x2 (min a max):', ...
        'Position', [100 300 200 30], ...
        'HorizontalAlignment', 'center', ...
        'FontSize', 12);

    x2MinField = uieditfield(fig, 'numeric', ...
        'Placeholder', 'Min x2', ...
        'Position', [100 260 90 30]);

    x2MaxField = uieditfield(fig, 'numeric', ...
        'Placeholder', 'Max x2', ...
        'Position', [210 260 90 30]);

    % Tlačítko: Nastavit počáteční hodnoty
    btnInit = uibutton(fig, ...
        'Text', 'Nastavit počáteční hodnoty', ...
        'Position', [100 200 200 40], ...
        'ButtonPushedFcn', @(btn, event) nastavPocatecniHodnoty());

    % Tlačítko: Zadání parametrů
    btn2 = uibutton(fig, ...
        'Text', 'Zadat parametry', ...
        'Position', [100 140 200 40], ...
        'ButtonPushedFcn', @(btn, event) zadatParametry());

    % Tlačítko: Spuštění algoritmu
    btn3 = uibutton(fig, ...
        'Text', 'Spustit algoritmus', ...
        'Position', [100 80 200 40], ...
        'ButtonPushedFcn', @(btn, event) spustitAlgoritmus());

    % Tlačítko: Výstupní výsledky
    btn4 = uibutton(fig, ...
        'Text', 'Zobrazit výsledky', ...
        'Position', [100 20 200 40], ...
        'ButtonPushedFcn', @(btn, event) zobrazitVysledky());
    
    % Funkce tlačítek
    function nastavPocatecniHodnoty()
        uialert(fig, 'Zde bude funkce pro nastavení počátečních hodnot.', 'Počáteční hodnoty');
    end

    function zadatParametry()
        uialert(fig, 'Zde bude funkce pro zadání parametrů.', 'Zadání parametrů');
    end

    function spustitAlgoritmus()
        % Načtení aktuálních hodnot z dropdown menu, textového pole a omezení
        selectedFunction = dropdownFun.Value;
        shape = dropdownShape.Value;
        sizeValue = sizeField.Value;

        x1Min = x1MinField.Value;
        x1Max = x1MaxField.Value;
        x2Min = x2MinField.Value;
        x2Max = x2MaxField.Value;

        % Kontrola, zda jsou hodnoty omezení validní
        if isempty(x1Min) || isempty(x1Max) || isempty(x2Min) || isempty(x2Max) || ...
           x1Min >= x1Max || x2Min >= x2Max
            uialert(fig, 'Chyba: Zadejte platné hodnoty pro omezení x1 a x2!', 'Chyba');
            return;
        end

        % Zobrazení informací (můžete nahradit výpočty nebo jinými funkcemi)
        message = sprintf(['Vybraná funkce: %s\nTvar okolí: %s\nVelikost: %.2f\n' ...
                           'x1: [%.2f, %.2f], x2: [%.2f, %.2f]'], ...
                          selectedFunction, shape, sizeValue, ...
                          x1Min, x1Max, x2Min, x2Max);
        uialert(fig, message, 'Spuštění algoritmu');
    end

    function zobrazitVysledky()
        uialert(fig, 'Zde bude funkce pro zobrazení výsledků.', 'Výsledky');
    end
end
